set(_CATKIN_CURRENT_PACKAGE "merge_pcl")
set(merge_pcl_VERSION "0.0.0")
set(merge_pcl_MAINTAINER "erush91 <erush91@todo.todo>")
set(merge_pcl_PACKAGE_FORMAT "2")
set(merge_pcl_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "pcl_ros" "pcl_conversions" "message_generation" "message_runtime")
set(merge_pcl_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "pcl_ros" "pcl_conversions")
set(merge_pcl_BUILDTOOL_DEPENDS "catkin")
set(merge_pcl_BUILDTOOL_EXPORT_DEPENDS )
set(merge_pcl_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "pcl_ros" "pcl_conversions")
set(merge_pcl_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "pcl_ros" "pcl_conversions")
set(merge_pcl_TEST_DEPENDS )
set(merge_pcl_DOC_DEPENDS )
set(merge_pcl_URL_WEBSITE "")
set(merge_pcl_URL_BUGTRACKER "")
set(merge_pcl_URL_REPOSITORY "")
set(merge_pcl_DEPRECATED "")