set(_CATKIN_CURRENT_PACKAGE "octomap_to_pcl")
set(octomap_to_pcl_VERSION "0.0.0")
set(octomap_to_pcl_MAINTAINER "erush91 <erush91@todo.todo>")
set(octomap_to_pcl_PACKAGE_FORMAT "2")
set(octomap_to_pcl_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "octomap" "octomap_msgs" "octomap_ros" "pcl_ros" "pcl_conversions" "message_generation" "message_runtime")
set(octomap_to_pcl_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "octomap" "octomap_msgs" "octomap_ros" "pcl_ros" "pcl_conversions")
set(octomap_to_pcl_BUILDTOOL_DEPENDS "catkin")
set(octomap_to_pcl_BUILDTOOL_EXPORT_DEPENDS )
set(octomap_to_pcl_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "octomap" "octomap_msgs" "octomap_ros" "pcl_ros" "pcl_conversions")
set(octomap_to_pcl_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "octomap" "octomap_msgs" "octomap_ros" "pcl_ros" "pcl_conversions")
set(octomap_to_pcl_TEST_DEPENDS )
set(octomap_to_pcl_DOC_DEPENDS )
set(octomap_to_pcl_URL_WEBSITE "")
set(octomap_to_pcl_URL_BUGTRACKER "")
set(octomap_to_pcl_URL_REPOSITORY "")
set(octomap_to_pcl_DEPRECATED "")